variables:
  GITLAB_FEATURES: '${GITLAB_FEATURES},dependency_scanning'

include:
  - template: Dependency-Scanning.gitlab-ci.yml

stages:
  - build
  - test
  - deploy

.node:
  image: node:16

  before_script:
    - '[[ -d node_modules ]] || npm ci --progress=false'

  cache:
    - key:
        files:
          - package-lock.json
      paths:
        - node_modules

build:
  stage: build
  extends: .node
  script:
    - npm run production
  artifacts:
    paths:
      - public/assets
      - public/mix-manifest.json
    expire_in: 1 day

prettier:
  extends: .node
  allow_failure: true
  stage: test
  script:
    - npm run prettier-check

eslint:
  extends: .node
  allow_failure: true
  stage: test
  script:
    - npm run eslint-check

stylelint:
  extends: .node
  allow_failure: true
  stage: test
  script:
    - npm run stylelint-check

pages:
  stage: deploy
  script:
    - '[ $CI_PAGES_URL ] && find public -type f -name "*.html" -exec sed -i "s@/assets/@$CI_PAGES_URL/assets/@g" {} \;'
  artifacts:
    paths:
      - public
  only:
    - main
